### ISSUE TITLE
[THEMOVIES-001] Add Fragments

### ISSUE THREAD

**Issue by BruceTrindade** [daniloqueirooz/AppTheMovies#1]
1 - Adicionar as dependencias do fragment | navigation - Jetpack Components - para adicionar os fragments de home e details. 
2 - Criar o Nav Graph 
3 - Colocar o NavHost na Main Activity
4 - Garantir a navegação da main activity para a home
5 - Construir a home (rodar para garantir que os filmes mockados estão sendo listados)

**Comment by BruceTrindade** [comment]
https://developer.android.com/guide/navigation/navigation-getting-started?hl=pt-br

**Comment by daniloqueirooz** [comment]
finished all task
